In [3]:
from math import *
import numpy as np
import matplotlib.pyplot as plt

In [4]:
25*2.56

64.0

In [5]:
A = np.array([[9.,1.,1.,1.],[2.,4.,6.,8.],[3.,9.,6.,12.],[4.,2.,6.,8.]])

for i in range(1,4):
    A[0]= A[0]/A[0,0]
    A[i]= A[i] - (A[0] * A[i,0])
    
for j in range(2,4):
    A[1]= A[1]/A[1,1]
    A[j]= A[j] - (A[1] * A[j,1])
    
for k in range(3,4):
    A[2]= A[2]/A[2,2]
    A[k]= A[k] - (A[2] * A[k,2])
print(A)

[[ 1.          0.11111111  0.11111111  0.11111111]
 [ 0.          1.          1.52941176  2.05882353]
 [-0.         -0.          1.          0.81395349]
 [ 0.          0.          0.          1.76744186]]


In [6]:
A = np.array([[9.,1.,1.,1.],[2.,4.,6.,8.],[3.,9.,6.,12.],[4.,2.,6.,8.]])
n = len(A)-1
for h in range(n):
    for l in range(h+1,n+1):
        A[h]= A[h]/A[h,h]
        A[l]= A[l] - (A[h] * A[l,h])
print(A)

[[ 1.          0.11111111  0.11111111  0.11111111]
 [ 0.          1.          1.52941176  2.05882353]
 [-0.         -0.          1.          0.81395349]
 [ 0.          0.          0.          1.76744186]]
