In [12]:
from math import *
import numpy as np
import matplotlib.pyplot as plt

In [106]:
D = np.array([[106.8],[177.2],[279.2]],float)
U = np.array([[25,5,1],[64,8,1],[144,12,1]],float)
L= np.identity(len(U))
n = len(U)-1
for h in range(n):
    for l in range(h+1,n+1):
        L[l,h] = U[l,h]/U[h,h]
        
        D0= D[h]/U[h,h]
        D[l]= D[l] - (D0 * U[l,h])
        
        U0= U[h]/U[h,h]
        U[l]= U[l] - (U0 * U[l,h])

print(U)
print(D)
        
X = np.empty(n, float)
for m in range(n-1, -1, -1):
    X[m]= D[m]/U[m,m]
print(X)

[[25.    5.    1.  ]
 [ 0.   -4.8  -1.56]
 [ 0.    0.    0.7 ]]
[[106.8  ]
 [-96.208]
 [  0.76 ]]


In [104]:
x = empty(N, float)
for m in range(N-1, -1, -1):
    x[m] = v[m]
    for i in range(m+1, N):
        x[m] -= A[m, i] * x[i]

[0.  0.  0.7]


In [89]:
D = np.array([[-4],[3],[9],[7]],float)
U = np.array([[2,1,4,1],[3,4,-1,-1],[1,-4,1,5],[2,-2,1,3]],float)
L= np.identity(len(U))
n = len(U)-1
for h in range(n):
    for l in range(h+1,n+1):
        L[l,h] = U[l,h]/U[h,h]
        
        y= D[h]/U[h,h]
        D[l]= D[l] - (y * U[l,h])
        
        x= U[h]/U[h,h]
        U[l]= U[l] - (x * U[l,h])

print(U)
print(L)
print(D)

[[  2.    1.    4.    1. ]
 [  0.    2.5  -7.   -2.5]
 [  0.    0.  -13.6   0. ]
 [  0.    0.    0.   -1. ]]
[[ 1.          0.          0.          0.        ]
 [ 1.5         1.          0.          0.        ]
 [ 0.5        -1.8         1.          0.        ]
 [ 1.         -1.2         0.83823529  1.        ]]
[[-4. ]
 [ 9. ]
 [27.2]
 [-1. ]]


In [90]:
np.dot(L,U)

array([[ 2.,  1.,  4.,  1.],
       [ 3.,  4., -1., -1.],
       [ 1., -4.,  1.,  5.],
       [ 2., -2.,  1.,  3.]])